"""update patient demographics

Revision ID: 2ce5d1c8d9b4
Revises: 622166a23201
Create Date: 2026-10-03 21:35:17.123813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce5d1c8d9b4'
down_revision: Union[str, Sequence[str], None] = '622166a23201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'patients',
        sa.Column('preferred_name', sa.String(), nullable=True)
    )

    op.add_column(
        'patients',
        sa.Column('custom_pronouns', sa.String(), nullable=True)
    )

    op.execute(
        sa.text(
            "UPDATE patients "
            "SET sex_at_birth = 'unknown' "
            "WHERE sex_at_birth IS NULL"
        )
    )

    op.alter_column(
        'patients',
        'sex_at_birth',
        existing_type=sa.VARCHAR(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'sex_at_birth',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('patients', 'custom_pronouns')
    op.drop_column('patients', 'preferred_name')
    # ### end Alembic commands ###
