"""add patient demographic fields

Revision ID: 622166a23201
Revises: 74c781aecd73
Create Date: 2026-10-03 12:52:57.387390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622166a23201'
down_revision: Union[str, Sequence[str], None] = '74c781aecd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('suffix', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('pronouns', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('sex_at_birth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'sex_at_birth')
    op.drop_column('patients', 'pronouns')
    op.drop_column('patients', 'suffix')
    op.drop_column('patients', 'middle_name')
    # ### end Alembic commands ###
